// <auto-generated />
namespace LibraryDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class tags_category_for_book2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tags_category_for_book2));
        
        string IMigrationMetadata.Id
        {
            get { return "201404120707434_tags_category_for_book2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
